version: "3.8"

services:
    api:
        container_name: nest-boilerplate-api
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/home/api
            - /home/api/node_modules
        networks:
            - nest-boilerplate-network

    pgadmin:
        container_name: nest-boilerplate-pgadmin
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com.br'
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 16543:80
        depends_on:
            - postgres
        networks:
            - nest-boilerplate-network

    postgres:
        container_name: nest-boilerplate-postgres
        image: postgres:latest
        ports:
            - "3500:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: root
            POSTGRES_DB: db
        networks:
            - nest-boilerplate-network

networks:
    nest-boilerplate-network:
